<?php

declare(strict_types=1);

namespace Otherguy\Currency;

enum Currency: string
{
    case AED = 'AED';
    case AFN = 'AFN';
    case ALL = 'ALL';
    case AMD = 'AMD';
    case ANG = 'ANG';
    case AOA = 'AOA';
    case ARS = 'ARS';
    case AUD = 'AUD';
    case AWG = 'AWG';
    case AZN = 'AZN';
    case BAM = 'BAM';
    case BBD = 'BBD';
    case BDT = 'BDT';
    case BGN = 'BGN';
    case BHD = 'BHD';
    case BIF = 'BIF';
    case BMD = 'BMD';
    case BND = 'BND';
    case BOB = 'BOB';
    case BRL = 'BRL';
    case BSD = 'BSD';
    case BTC = 'BTC';
    case BTN = 'BTN';
    case BWP = 'BWP';
    case BYR = 'BYR';
    case BYN = 'BYN';
    case BZD = 'BZD';
    case CAD = 'CAD';
    case CDF = 'CDF';
    case CHF = 'CHF';
    case CLF = 'CLF';
    case CLP = 'CLP';
    case CNY = 'CNY';
    case COP = 'COP';
    case CRC = 'CRC';
    case CUC = 'CUC';
    case CUP = 'CUP';
    case CVE = 'CVE';
    case CZK = 'CZK';
    case DJF = 'DJF';
    case DKK = 'DKK';
    case DOP = 'DOP';
    case DZD = 'DZD';
    case EGP = 'EGP';
    case ERN = 'ERN';
    case ETB = 'ETB';
    case EUR = 'EUR';
    case FJD = 'FJD';
    case FKP = 'FKP';
    case GBP = 'GBP';
    case GEL = 'GEL';
    case GGP = 'GGP';
    case GHS = 'GHS';
    case GIP = 'GIP';
    case GMD = 'GMD';
    case GNF = 'GNF';
    case GTQ = 'GTQ';
    case GYD = 'GYD';
    case HKD = 'HKD';
    case HNL = 'HNL';
    case HRK = 'HRK';
    case HTG = 'HTG';
    case HUF = 'HUF';
    case IDR = 'IDR';
    case ILS = 'ILS';
    case IMP = 'IMP';
    case INR = 'INR';
    case IQD = 'IQD';
    case IRR = 'IRR';
    case ISK = 'ISK';
    case JEP = 'JEP';
    case JMD = 'JMD';
    case JOD = 'JOD';
    case JPY = 'JPY';
    case KES = 'KES';
    case KGS = 'KGS';
    case KHR = 'KHR';
    case KMF = 'KMF';
    case KPW = 'KPW';
    case KRW = 'KRW';
    case KWD = 'KWD';
    case KYD = 'KYD';
    case KZT = 'KZT';
    case LAK = 'LAK';
    case LBP = 'LBP';
    case LKR = 'LKR';
    case LRD = 'LRD';
    case LSL = 'LSL';
    case LTL = 'LTL';
    case LVL = 'LVL';
    case LYD = 'LYD';
    case MAD = 'MAD';
    case MDL = 'MDL';
    case MGA = 'MGA';
    case MKD = 'MKD';
    case MMK = 'MMK';
    case MNT = 'MNT';
    case MOP = 'MOP';
    case MRO = 'MRO';
    case MUR = 'MUR';
    case MVR = 'MVR';
    case MWK = 'MWK';
    case MXN = 'MXN';
    case MYR = 'MYR';
    case MZN = 'MZN';
    case NAD = 'NAD';
    case NGN = 'NGN';
    case NIO = 'NIO';
    case NOK = 'NOK';
    case NPR = 'NPR';
    case NZD = 'NZD';
    case OMR = 'OMR';
    case PAB = 'PAB';
    case PEN = 'PEN';
    case PGK = 'PGK';
    case PHP = 'PHP';
    case PKR = 'PKR';
    case PLN = 'PLN';
    case PYG = 'PYG';
    case QAR = 'QAR';
    case RON = 'RON';
    case RSD = 'RSD';
    case RUB = 'RUB';
    case RWF = 'RWF';
    case SAR = 'SAR';
    case SBD = 'SBD';
    case SCR = 'SCR';
    case SDG = 'SDG';
    case SEK = 'SEK';
    case SGD = 'SGD';
    case SHP = 'SHP';
    case SLL = 'SLL';
    case SOS = 'SOS';
    case SRD = 'SRD';
    case STD = 'STD';
    case SVC = 'SVC';
    case SYP = 'SYP';
    case SZL = 'SZL';
    case THB = 'THB';
    case TJS = 'TJS';
    case TMT = 'TMT';
    case TND = 'TND';
    case TOP = 'TOP';
    case TRY = 'TRY';
    case TTD = 'TTD';
    case TWD = 'TWD';
    case TZS = 'TZS';
    case UAH = 'UAH';
    case UGX = 'UGX';
    case USD = 'USD';
    case UYU = 'UYU';
    case UZS = 'UZS';
    case VEF = 'VEF';
    case VND = 'VND';
    case VUV = 'VUV';
    case WST = 'WST';
    case XAF = 'XAF';
    case XAG = 'XAG';
    case XAU = 'XAU';
    case XCD = 'XCD';
    case XDR = 'XDR';
    case XOF = 'XOF';
    case XPF = 'XPF';
    case YER = 'YER';
    case ZAR = 'ZAR';
    case ZMW = 'ZMW';
    case ZWL = 'ZWL';

    public static function tryFromCode(string $code): ?self
    {
        return self::tryFrom($code);
    }

    public function displayName(): string
    {
        return match ($this) {
            self::AED => 'United Arab Emirates Dirham',
            self::AFN => 'Afghan Afghani',
            self::ALL => 'Albanian Lek',
            self::AMD => 'Armenian Dram',
            self::ANG => 'Netherlands Antillean Guilder',
            self::AOA => 'Angolan Kwanza',
            self::ARS => 'Argentine Peso',
            self::AUD => 'Australian Dollar',
            self::AWG => 'Aruban Florin',
            self::AZN => 'Azerbaijani Manat',
            self::BAM => 'Bosnia Herzegovina Convertible Mark',
            self::BBD => 'Barbadian Dollar',
            self::BDT => 'Bangladeshi Taka',
            self::BGN => 'Bulgarian Lev',
            self::BHD => 'Bahraini Dinar',
            self::BIF => 'Burundian Franc',
            self::BMD => 'Bermudan Dollar',
            self::BND => 'Brunei Dollar',
            self::BOB => 'Bolivian Boliviano',
            self::BRL => 'Brazilian Real',
            self::BSD => 'Bahamian Dollar',
            self::BTC => 'Bitcoin',
            self::BTN => 'Bhutanese Ngultrum',
            self::BWP => 'Botswanan Pula',
            self::BYR => 'Belarusian Ruble',
            self::BYN => 'New Belarusian Ruble',
            self::BZD => 'Belize Dollar',
            self::CAD => 'Canadian Dollar',
            self::CDF => 'Congolese Franc',
            self::CHF => 'Swiss Franc',
            self::CLF => 'Chilean Unit of Account',
            self::CLP => 'Chilean Peso',
            self::CNY => 'Chinese Yuan',
            self::COP => 'Colombian Peso',
            self::CRC => 'Costa Rican Colón',
            self::CUC => 'Cuban Convertible Peso',
            self::CUP => 'Cuban Peso',
            self::CVE => 'Cape Verdean Escudo',
            self::CZK => 'Czech Republic Koruna',
            self::DJF => 'Djiboutian Franc',
            self::DKK => 'Danish Krone',
            self::DOP => 'Dominican Peso',
            self::DZD => 'Algerian Dinar',
            self::EGP => 'Egyptian Pound',
            self::ERN => 'Eritrean Nakfa',
            self::ETB => 'Ethiopian Birr',
            self::EUR => 'Euro',
            self::FJD => 'Fijian Dollar',
            self::FKP => 'Falkland Islands Pound',
            self::GBP => 'British Pound Sterling',
            self::GEL => 'Georgian Lari',
            self::GGP => 'Guernsey Pound',
            self::GHS => 'Ghanaian Cedi',
            self::GIP => 'Gibraltar Pound',
            self::GMD => 'Gambian Dalasi',
            self::GNF => 'Guinean Franc',
            self::GTQ => 'Guatemalan Quetzal',
            self::GYD => 'Guyanaese Dollar',
            self::HKD => 'Hong Kong Dollar',
            self::HNL => 'Honduran Lempira',
            self::HRK => 'Croatian Kuna',
            self::HTG => 'Haitian Gourde',
            self::HUF => 'Hungarian Forint',
            self::IDR => 'Indonesian Rupiah',
            self::ILS => 'Israeli New Sheqel',
            self::IMP => 'Manx pound',
            self::INR => 'Indian Rupee',
            self::IQD => 'Iraqi Dinar',
            self::IRR => 'Iranian Rial',
            self::ISK => 'Icelandic Króna',
            self::JEP => 'Jersey Pound',
            self::JMD => 'Jamaican Dollar',
            self::JOD => 'Jordanian Dinar',
            self::JPY => 'Japanese Yen',
            self::KES => 'Kenyan Shilling',
            self::KGS => 'Kyrgystani Som',
            self::KHR => 'Cambodian Riel',
            self::KMF => 'Comorian Franc',
            self::KPW => 'North Korean Won',
            self::KRW => 'South Korean Won',
            self::KWD => 'Kuwaiti Dinar',
            self::KYD => 'Cayman Islands Dollar',
            self::KZT => 'Kazakhstani Tenge',
            self::LAK => 'Laotian Kip',
            self::LBP => 'Lebanese Pound',
            self::LKR => 'Sri Lankan Rupee',
            self::LRD => 'Liberian Dollar',
            self::LSL => 'Lesotho Loti',
            self::LTL => 'Lithuanian Litas',
            self::LVL => 'Latvian Lats',
            self::LYD => 'Libyan Dinar',
            self::MAD => 'Moroccan Dirham',
            self::MDL => 'Moldovan Leu',
            self::MGA => 'Malagasy Ariary',
            self::MKD => 'Macedonian Denar',
            self::MMK => 'Myanma Kyat',
            self::MNT => 'Mongolian Tugrik',
            self::MOP => 'Macanese Pataca',
            self::MRO => 'Mauritanian Ouguiya',
            self::MUR => 'Mauritian Rupee',
            self::MVR => 'Maldivian Rufiyaa',
            self::MWK => 'Malawian Kwacha',
            self::MXN => 'Mexican Peso',
            self::MYR => 'Malaysian Ringgit',
            self::MZN => 'Mozambican Metical',
            self::NAD => 'Namibian Dollar',
            self::NGN => 'Nigerian Naira',
            self::NIO => 'Nicaraguan Córdoba',
            self::NOK => 'Norwegian Krone',
            self::NPR => 'Nepalese Rupee',
            self::NZD => 'New Zealand Dollar',
            self::OMR => 'Omani Rial',
            self::PAB => 'Panamanian Balboa',
            self::PEN => 'Peruvian Nuevo Sol',
            self::PGK => 'Papua New Guinean Kina',
            self::PHP => 'Philippine Peso',
            self::PKR => 'Pakistani Rupee',
            self::PLN => 'Polish Zloty',
            self::PYG => 'Paraguayan Guarani',
            self::QAR => 'Qatari Rial',
            self::RON => 'Romanian Leu',
            self::RSD => 'Serbian Dinar',
            self::RUB => 'Russian Ruble',
            self::RWF => 'Rwandan Franc',
            self::SAR => 'Saudi Riyal',
            self::SBD => 'Solomon Islands Dollar',
            self::SCR => 'Seychellois Rupee',
            self::SDG => 'Sudanese Pound',
            self::SEK => 'Swedish Krona',
            self::SGD => 'Singapore Dollar',
            self::SHP => 'Saint Helena Pound',
            self::SLL => 'Sierra Leonean Leone',
            self::SOS => 'Somali Shilling',
            self::SRD => 'Surinamese Dollar',
            self::STD => 'São Tomé and Príncipe Dobra',
            self::SVC => 'Salvadoran Colón',
            self::SYP => 'Syrian Pound',
            self::SZL => 'Swazi Lilangeni',
            self::THB => 'Thai Baht',
            self::TJS => 'Tajikistani Somoni',
            self::TMT => 'Turkmenistani Manat',
            self::TND => 'Tunisian Dinar',
            self::TOP => 'Tongan Paʻanga',
            self::TRY => 'Turkish Lira',
            self::TTD => 'Trinidad and Tobago Dollar',
            self::TWD => 'New Taiwan Dollar',
            self::TZS => 'Tanzanian Shilling',
            self::UAH => 'Ukrainian Hryvnia',
            self::UGX => 'Ugandan Shilling',
            self::USD => 'United States Dollar',
            self::UYU => 'Uruguayan Peso',
            self::UZS => 'Uzbekistan Som',
            self::VEF => 'Venezuelan Bolívar Fuerte',
            self::VND => 'Vietnamese Dong',
            self::VUV => 'Vanuatu Vatu',
            self::WST => 'Samoan Tala',
            self::XAF => 'CFA Franc BEAC',
            self::XAG => 'Silver',
            self::XAU => 'Gold',
            self::XCD => 'East Caribbean Dollar',
            self::XDR => 'Special Drawing Rights',
            self::XOF => 'CFA Franc BCEAO',
            self::XPF => 'CFP Franc',
            self::YER => 'Yemeni Rial',
            self::ZAR => 'South African Rand',
            self::ZMW => 'Zambian Kwacha',
            self::ZWL => 'Zimbabwean Dollar',
        };
    }

    /**
     * Coerce a string code or Currency enum to its uppercase string code.
     */
    public static function code(string|self $code): string
    {
        return $code instanceof self ? $code->value : $code;
    }
}
